"""
Definição central dos temas visuais do catálogo.

Cada tema vira um conjunto de CSS custom properties, aplicadas via
`{% include %}` tanto no picker de configurações quanto na vitrine pública.
Isso substitui as cadeias gigantes de `{% if lojista.tema == ... %}`
espalhadas pelo template — pra trocar uma cor ou criar um tema novo,
mexe só aqui.
"""

TEMAS = {
    "minimal_nordic": {
        "label": "Minimal Nordic",
        "mood": "Moda, boutique, joalheria",
        "descricao": "Minimalista, tipografia forte em preto e branco.",
        "escuro": False,
        "bg": "#FAFAFA",
        "surface": "#FFFFFF",
        "border": "#E5E5E5",
        "texto": "#111111",
        "texto_muted": "#6B7280",
        "primaria": "#111111",
        "primaria_hover": "#000000",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "modern_emerald": {
        "label": "Emerald Clean",
        "mood": "Delivery, alimentos, farmácia",
        "descricao": "Visual limpo e dinâmico com destaque em verde.",
        "escuro": False,
        "bg": "#F0FDF4",
        "surface": "#FFFFFF",
        "border": "#D1FAE5",
        "texto": "#111827",
        "texto_muted": "#6B7280",
        "primaria": "#059669",
        "primaria_hover": "#047857",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "dark_neon": {
        "label": "Dark Premium",
        "mood": "Barbearia, eletrônicos, tabacaria",
        "descricao": "Modo escuro sofisticado com destaques em neon.",
        "escuro": True,
        "bg": "#030712",
        "surface": "#111827",
        "border": "#1F2937",
        "texto": "#F9FAFB",
        "texto_muted": "#9CA3AF",
        "primaria": "#4ADE80",
        "primaria_hover": "#22C55E",
        "texto_primaria": "#052E16",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "warm_sunset": {
        "label": "Warm Sunset",
        "mood": "Hamburgueria, doceria",
        "descricao": "Tons quentes de laranja e âmbar, desperta apetite.",
        "escuro": False,
        "bg": "#FFFBEB",
        "surface": "#FFFFFF",
        "border": "#FDE68A",
        "texto": "#1C1917",
        "texto_muted": "#78716C",
        "primaria": "#D97706",
        "primaria_hover": "#B45309",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "vibrant_purple": {
        "label": "Vibrant Tech",
        "mood": "Tech, moderno, apps",
        "descricao": "Roxo vibrante com toque futurista.",
        "escuro": False,
        "bg": "#FAF5FF",
        "surface": "#FFFFFF",
        "border": "#E9D5FF",
        "texto": "#1E1B2E",
        "texto_muted": "#6B7280",
        "primaria": "#9333EA",
        "primaria_hover": "#7E22CE",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "candy_pastels": {
        "label": "Candy Pastels",
        "mood": "Confeitaria, mimos, papelaria",
        "descricao": "Rosa pastel delicado.",
        "escuro": False,
        "bg": "#FDF2F8",
        "surface": "#FFFFFF",
        "border": "#FBCFE8",
        "texto": "#3F2A33",
        "texto_muted": "#9D7482",
        "primaria": "#F472B6",
        "primaria_hover": "#EC4899",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "rustic_earth": {
        "label": "Rustic Earth",
        "mood": "Cafeteria, padaria, artesanal",
        "descricao": "Cores terrosas e acolhedoras.",
        "escuro": False,
        "bg": "#F5F5F4",
        "surface": "#FFFFFF",
        "border": "#E7E5E4",
        "texto": "#292524",
        "texto_muted": "#78716C",
        "primaria": "#78350F",
        "primaria_hover": "#5C2A0C",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "sport_fire": {
        "label": "Sport Fire",
        "mood": "Suplementos, moda fitness",
        "descricao": "Escuro com vermelho vibrante.",
        "escuro": True,
        "bg": "#18181B",
        "surface": "#27272A",
        "border": "#3F3F46",
        "texto": "#FAFAFA",
        "texto_muted": "#A1A1AA",
        "primaria": "#DC2626",
        "primaria_hover": "#B91C1C",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "ocean_breeze": {
        "label": "Ocean Breeze",
        "mood": "Frescor, sorveteria, praia",
        "descricao": "Azul claro e refrescante.",
        "escuro": False,
        "bg": "#F0F9FF",
        "surface": "#FFFFFF",
        "border": "#BAE6FD",
        "texto": "#0C4A6E",
        "texto_muted": "#64748B",
        "primaria": "#0891B2",
        "primaria_hover": "#0E7490",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "luxury_gold": {
        "label": "Luxury Gold",
        "mood": "Joalheria, vinhos, artigos de luxo",
        "descricao": "Preto e dourado, estética premium.",
        "escuro": True,
        "bg": "#0A0A0A",
        "surface": "#171717",
        "border": "#3A3226",
        "texto": "#FDE9C0",
        "texto_muted": "#B8A47C",
        "primaria": "#FBBF24",
        "primaria_hover": "#F59E0B",
        "texto_primaria": "#1C1503",
        "fonte": "'Playfair Display', serif",
    },
    "cyber_punk": {
        "label": "Cyber Punk",
        "mood": "Games, tech, geek",
        "descricao": "Futurista, roxo e magenta neon.",
        "escuro": True,
        "bg": "#020617",
        "surface": "#1E1B3A",
        "border": "#4C1D95",
        "texto": "#F5D0FE",
        "texto_muted": "#A78BFA",
        "primaria": "#D946EF",
        "primaria_hover": "#C026D3",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "sunset_drive": {
        "label": "Sunset Drive",
        "mood": "Moda praia, açaí, verão",
        "descricao": "Laranja coral vibrante e ensolarado.",
        "escuro": False,
        "bg": "#FFF7ED",
        "surface": "#FFFFFF",
        "border": "#FED7AA",
        "texto": "#431407",
        "texto_muted": "#78716C",
        "primaria": "#F97316",
        "primaria_hover": "#EA580C",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "mint_fresh": {
        "label": "Mint Fresh",
        "mood": "Estética, cosméticos naturais, saúde",
        "descricao": "Verde menta limpo e revigorante.",
        "escuro": False,
        "bg": "#F0FDFA",
        "surface": "#FFFFFF",
        "border": "#99F6E4",
        "texto": "#134E4A",
        "texto_muted": "#5EAAA0",
        "primaria": "#14B8A6",
        "primaria_hover": "#0D9488",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
    "vintage_craft": {
        "label": "Vintage Craft",
        "mood": "Adega, couros, charutaria",
        "descricao": "Rústico e sofisticado, bordô e marfim.",
        "escuro": True,
        "bg": "#1C1917",
        "surface": "#292524",
        "border": "#44403C",
        "texto": "#FDF4E3",
        "texto_muted": "#C4B7A6",
        "primaria": "#B45309",
        "primaria_hover": "#92400E",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Playfair Display', serif",
    },
    "royal_blue": {
        "label": "Royal Blue",
        "mood": "Serviços, fardamentos, escritórios",
        "descricao": "Azul corporativo clássico e sóbrio.",
        "escuro": False,
        "bg": "#EFF6FF",
        "surface": "#FFFFFF",
        "border": "#BFDBFE",
        "texto": "#0F172A",
        "texto_muted": "#64748B",
        "primaria": "#2563EB",
        "primaria_hover": "#1D4ED8",
        "texto_primaria": "#FFFFFF",
        "fonte": "'Plus Jakarta Sans', sans-serif",
    },
}

TEMA_PADRAO = "minimal_nordic"


def get_tema(slug):
    return TEMAS.get(slug, TEMAS[TEMA_PADRAO])
