# Generated by Django 6.0.7 on 2026-07-27 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Usado no link: innosoft.com.br/slug-da-loja', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('whatsapp', models.CharField(help_text='Ex: 5535999999999 (Apenas números)', max_length=20)),
                ('mensagem_padrao', models.TextField(default='Olá! Gostaria de fazer o seguinte pedido:\n\n{pedido}')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='catalogo.lojista')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('foto', models.ImageField(upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='catalogo.categoria')),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='catalogo.lojista')),
            ],
        ),
    ]
