# Generated by Django 6.0.7 on 2026-07-29 19:55

import catalogo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('tema', models.CharField(choices=[('modern_emerald', 'Emerald Clean (Verde & Padrão)'), ('dark_neon', 'Dark Premium (Escuro & Neon)'), ('warm_sunset', 'Warm Sunset (Laranja & Gourmet)'), ('minimal_nordic', 'Minimal Nordic (Cinza & Elegante)'), ('vibrant_purple', 'Vibrant Tech (Roxo & Moderno)'), ('candy_pastels', 'Candy Pastels (Rosa & Suave)'), ('rustic_earth', 'Rustic Earth (Café & Artesanal)'), ('sport_fire', 'Sport Fire (Preto & Vermelho)'), ('ocean_breeze', 'Ocean Breeze (Azul & Frescor)'), ('luxury_gold', 'Luxury Gold (Preto & Dourado)'), ('cyber_punk', 'Cyber Punk (Roxo & Magenta Neon)'), ('sunset_drive', 'Sunset Drive (Laranja & Coral)'), ('mint_fresh', 'Mint Fresh (Menta & Saúde)'), ('vintage_craft', 'Vintage Craft (Vinho & Retrô)'), ('royal_blue', 'Royal Blue (Azul & Corporativo)')], default='minimal_nordic', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='catalogo.lojista')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=catalogo.models.caminho_foto_produto)),
                ('foto2', models.ImageField(blank=True, null=True, upload_to=catalogo.models.caminho_foto_produto)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='catalogo.categoria')),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='catalogo.lojista')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_variacao', to='catalogo.lojista')),
            ],
            options={
                'unique_together': {('lojista', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalogo.produto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.tipovariacao')),
            ],
        ),
        migrations.CreateModel(
            name='ValorVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalogo.tipovariacao')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('tipo', 'nome')},
            },
        ),
    ]
