# Generated by Django 6.0.7 on 2026-07-27 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_base',
        ),
        migrations.RemoveField(
            model_name='lojista',
            name='mensagem_padrao',
        ),
        migrations.AlterField(
            model_name='lojista',
            name='slug',
            field=models.SlugField(help_text='Link: innosoft.com.br/slug-da-loja', unique=True),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lojista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='whatsapp',
            field=models.CharField(help_text='Apenas números com DDD', max_length=20),
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(blank=True, help_text='Ex: P, M, G, 42', max_length=20)),
                ('cor', models.CharField(blank=True, help_text='Ex: Azul, Preto', max_length=30)),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor extra caso mude o preço', max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalogo.produto')),
            ],
        ),
    ]
