# Generated by Django 6.0.7 on 2026-07-29 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variacaoproduto',
            unique_together={('produto', 'tipo', 'valor')},
        ),
    ]
