# Generated by Django 6.0.7 on 2026-07-27 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_preco_produto_preco_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lojista',
            name='logo',
        ),
        migrations.AddField(
            model_name='lojista',
            name='tema',
            field=models.CharField(choices=[('modern_emerald', 'Emerald Clean (Verde & Padrão)'), ('dark_neon', 'Dark Premium (Escuro & Neon)'), ('warm_sunset', 'Warm Sunset (Laranja & Gourmet)'), ('minimal_nordic', 'Minimal Nordic (Cinza & Elegante)'), ('vibrant_purple', 'Vibrant Tech (Roxo & Moderno)')], default='minimal_nordic', max_length=30),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
