# Generated by Django 6.0.7 on 2026-08-12 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_variacaoproduto_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('lojista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='catalogo.lojista')),
            ],
            options={
                'verbose_name': 'Inscrição Push',
                'verbose_name_plural': 'Inscrições Push',
                'indexes': [models.Index(fields=['lojista', 'ativo'], name='catalogo_pu_lojista_ac3a0c_idx')],
            },
        ),
    ]
