# Generated by Django 6.0.7 on 2026-07-28 01:56

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_lojista_logo_lojista_tema_alter_lojista_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to=catalogo.models.caminho_foto_produto),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='tema',
            field=models.CharField(choices=[('modern_emerald', 'Emerald Clean (Verde & Padrão)'), ('dark_neon', 'Dark Premium (Escuro & Neon)'), ('warm_sunset', 'Warm Sunset (Laranja & Gourmet)'), ('minimal_nordic', 'Minimal Nordic (Cinza & Elegante)'), ('vibrant_purple', 'Vibrant Tech (Roxo & Moderno)'), ('candy_pastels', 'Candy Pastels (Rosa & Suave)'), ('rustic_earth', 'Rustic Earth (Café & Artesanal)'), ('sport_fire', 'Sport Fire (Preto & Vermelho)'), ('ocean_breeze', 'Ocean Breeze (Azul & Frescor)'), ('luxury_gold', 'Luxury Gold (Preto & Dourado)'), ('cyber_punk', 'Cyber Punk (Roxo & Magenta Neon)'), ('sunset_drive', 'Sunset Drive (Laranja & Coral)'), ('mint_fresh', 'Mint Fresh (Menta & Saúde)'), ('vintage_craft', 'Vintage Craft (Vinho & Retrô)'), ('royal_blue', 'Royal Blue (Azul & Corporativo)')], default='minimal_nordic', max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=catalogo.models.caminho_foto_produto),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
