# Generated by Django 6.0.7 on 2026-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojista',
            name='link_app_habilitado',
            field=models.BooleanField(default=True, verbose_name='Link de instalação do app (PWA)'),
        ),
        migrations.AddField(
            model_name='lojista',
            name='notificacoes_habilitadas',
            field=models.BooleanField(default=True, verbose_name='Ativar notificações'),
        ),
    ]
