# Generated by Django 6.0.7 on 2026-09-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_lojista_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojista',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
    ]
