# Generated by Django 6.0.7 on 2026-09-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_lojista_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojista',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
